### ISSUE TITLE
 : command not fount

### ISSUE THREAD

**Issue by Tizioincognit0** [Randomblock1/qemu-ios-installer#1]
I ran “qemuinstaller.sh” and “getraspbian.sh”. Then, when I ran “qemu-raspbian.sh”, i got the error “qemu-system-arm: command not found”.
In the image attached to this issue, it’s possible to see all the shell output.
I used NewTerm 2 on an iPhone X with iOS 12.2 jailbroken with Unc0ver 3.8.0b1.
![Shell output](https://user-images.githubusercontent.com/40031873/73609277-60543e00-45cc-11ea-82e4-2d0e5debefb6.JPG)

**Comment by Randomblock1** [comment]
Somehow, Git got interrupted. Make sure you leave it alone and have enough storage space available, then run qemu-installer again. Also, these scripts are meant to be run in /var/mobile, not Documents.

**Comment by Randomblock1** [comment]
Pushed a fix for a typo and some other stuff, try re downloading it

**Comment by Randomblock1** [comment]
Anyway, the main issue appears to be Git interrupted, not the script. So I’m going to close this.

**Comment by Tizioincognit0** [comment]
I downloaded the new version and I ran the scripts on /var/mobile but I got the same error. I don't think it's a storage space problem because I have 61.19 GB free.

**Comment by Randomblock1** [comment]
Have you tried running `git clone --branch testing https://github.com/MCApollo/MCApollo.github.io` in /var/mobile? Does it still fail? Try deleting the MCApollo folder and rerunning Git

**Comment by Tizioincognit0** [comment]
I did it and it didn't fail.

**Comment by Randomblock1** [comment]
I’m assuming it’s working fine, so I’m going to close this.
